### ISSUE TITLE
Question: .travis.yml sleep

### ISSUE THREAD

**Issue by pachonk** [NYULibraries/rooms#125]
I noticed that on line 10 and line 15 in your travis configuration you sleep for 30 seconds. I was just curious as to why it sleeps for such a long period of time before/after the script preparations.

**Comment by hab278** [comment]
@pachonk Back in the day, Travis was just getting started and was actually our 2nd CI tool. Travis wasn't very reliable and speed wasn't our real concern, since we had Jenkins as our primary CI tool. We made it `sleep 10` seconds to allow for `elasticsearch` to start, then another `sleep 10` to allow for the `bundle exec tire:import` to run. We quickly found out that it wasn't enough time, so we bumped it up to 30, and have kept it that way since.

**Comment by barnabyalter** [comment]
@pachonk @hab278 Also note that travis recommends this approach for ElasticSearch: https://docs.travis-ci.com/user/database-setup/#ElasticSearch.

And yes the exaggerated times are to catch any weirdness. Though please note that this is obsolete anyway because of the massive changes in the refactor branch: https://github.com/NYULibraries/rooms/blob/feature/replace_retire_with_elasticsearch-rails/.travis.yml
